// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZMTjfxZN_3ddZux4JqTnSwgT9UF9AsRM',
    appId: '1:443546116987:web:775de6caab9bff7385d3de',
    messagingSenderId: '443546116987',
    projectId: 'gdscufix2',
    authDomain: 'gdscufix2.firebaseapp.com',
    storageBucket: 'gdscufix2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJnPtaCIOpZFACwnXwYg9uigT7uJtZ5zU',
    appId: '1:443546116987:android:66607d655b1e2a7185d3de',
    messagingSenderId: '443546116987',
    projectId: 'gdscufix2',
    storageBucket: 'gdscufix2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1NnM_n3hgvzYRMQMLnvPiLcGOe14oxXM',
    appId: '1:443546116987:ios:f0d705fac504b8c185d3de',
    messagingSenderId: '443546116987',
    projectId: 'gdscufix2',
    storageBucket: 'gdscufix2.appspot.com',
    iosClientId: '443546116987-637ufvbo7sec1173pqiv3n9dn1q0v6pu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ufix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1NnM_n3hgvzYRMQMLnvPiLcGOe14oxXM',
    appId: '1:443546116987:ios:f0d705fac504b8c185d3de',
    messagingSenderId: '443546116987',
    projectId: 'gdscufix2',
    storageBucket: 'gdscufix2.appspot.com',
    iosClientId: '443546116987-637ufvbo7sec1173pqiv3n9dn1q0v6pu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ufix',
  );
}
